spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/soldo
    username: app_user
    password: app_pass
  jpa:
    show-sql: true

jwt:
  secret: G7f@2pX#9Zj$k8Lq*V*W1r5Bc4Y!u6Eo^Dc3MnpV0QzT

telegram:
  bot:
    secret: "1234"

logging:
  level:
    ru.savvy.soldo: TRACE
    org.springframework.security: TRACE
    org.springframework.security.web.FilterChainProxy: TRACE

swagger:
  username: admin
  password: admin
