package ru.savvy.soldo.model.enums;

public enum NotificationType {
    BOOKING_CONFIRMED,
    BOOKING_CANCELLED,
    PAYMENT_REMINDER,
    EVENT_REMINDER_1DAY,
    EVENT_REMINDER_1HOUR,
    EVENT_CHANGED,
    NEW_EVENT_AVAILABLE,
    WAITLIST_AVAILABLE
}